version: "3"
services:
  selenoid:
    container_name: selenoid_prueba
    network_mode: bridge
    image: "aerokube/selenoid:1.3.7"
    command: -limit 4 -retry-count 1000
    ports:
      - 4444:4444
    volumes:
      - ./config:/etc/selenoid:ro
      - /var/run/docker.sock:/var/run/docker.sock
  selenoid-ui:
    container_name: selenoid-ui_prueba
    network_mode: bridge
    image: "aerokube/selenoid-ui:1.4.3"
    command: ["-conf", "./config/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-selenoid-uri 'http://selenoid:4444'"]
    ports:
      - 8080:8080
    links:
      - selenoid